//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SedovaKravez
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedCard
    {
        public int IdClient { get; set; }
        public int IdPets { get; set; }
        public string Diagnosis { get; set; }
        public string Symptoms { get; set; }
        public string Comment { get; set; }
        public string PrescribedTreatment { get; set; }
        public string Tests { get; set; }
        public Nullable<int> MedicalSupplier { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
