//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SedovaKravez
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int IdOrder { get; set; }
        public int IdDoctor { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int Client { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual OrderItem OrderItem { get; set; }
    }
}
