//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SedovaKravez
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassEmpl
    {
        public string NumPass { get; set; }
        public string SerPass { get; set; }
        public int Employee { get; set; }
    
        public virtual Employee Employee1 { get; set; }
        public virtual Passport Passport { get; set; }
    }
}
